cooisColDict = {'/CUM/AUEST': 'Aut. szacow. kosztów',
 '/CUM/AUFPL_TMP': 'Nr mar. tech. oper.',
 '/CUM/CMNUM': 'Numer dokumentacji budowlanej',
 '/CUM/CUGUID': 'UUID',
 '/CUM/DESGUID': 'GUID projektu',
 '/CUM/DESNUM': 'Nr projektu EP',
 '/CUM/INDCU': 'Zlecenie EP',
 '/CUM/INTCUNR': 'Wewn. numer PE',
 '/CUM/IWERK_TLSEL': 'Zakład planowania',
 'ABGSL': 'Klucz rozgraniczenia',
 'ABKRS': 'Grupa przetwarzania',
 'ABUKR': 'Zamaw. jedn. gosp.',
 'ADRNRA': 'Numer adresu',
 'AEDAT': 'Data zm. danych podst. zlec.',
 'AENAM': 'Ost.zmien.przez',
 'AENNR': 'Numer zmiany',
 'AEZEIT': 'Godzina zmiany',
 'AKSTL': 'Zamawiające MPK',
 'APRIO': 'Priorytet',
 'ASTTX': 'Status użytkownika',
 'ATRKZ': 'Wskaźnik zlecenia',
 'AUART': 'Rodzaj zlecenia',
 'AUDISP': 'Rezerwacja/zgł. zap.',
 'AUFFX': 'Wskaźnik ustalania',
 'AUFLD': 'Data rozwinięcia',
 'AUFNR': 'Nr zlecenia',
 'AUTYP': 'Typ zlecenia',
 'AWSLS': 'Klucz odchylenia',
 'BEMOT': 'Wsk. pochodz.kosztów',
 'BERID': 'Obszar MRP',
 'BREAKS': 'Z uwzgl. przerw',
 'BSDIF': 'Różnica w dniach',
 'BSFAK': 'Współcz. potw. (PROZENT)',
 'BUKRS': 'Jednostka gosp.',
 'CALID': 'ID kalendarza zakł.',
 'CCKEY': 'Klucz zbier. kosztów',
 'CHARG': 'Partia',
 'CLAIM_CONTROL': 'Sterowanie tworzeniem reklamacji',
 'COLORDPROC': 'Rozwin. sieci zleceń',
 'CONF_KEY': 'Obiekt homogeniczny',
 'CONF_QUANT': 'Potwierdzony uzysk (CONF_UNIT)',
 'CONF_UNIT': 'Jednostka potwierdz. (=CONF_UNIT)',
 'COSTUPD': 'Aktualizacja kosztów',
 'CSPLIT': 'Schemat podziału',
 'CY_SEQNR': 'Numer sekwencyjny',
 'DELMIN': 'Opóźn. w minutach',
 'DISPO': 'Kontroler MRP',
 'ERDAT': 'Data wprowadzenia',
 'ERFZEIT': 'Godzina utworzenia',
 'ERNAM': 'Wprowadził(a)',
 'ETYPE': 'Klasa udziału',
 'FEVOR': 'Planista produkcji',
 'FHORI': 'Klucz horyzontu',
 'FREIZ': 'Horyzont zatw.',
 'FTRMI': 'Rzecz. termin zatw.',
 'FTRMP': 'Planowany ter. zatw.',
 'FTRMS': 'Termin zatw.wg harm.',
 'FTRPS': 'Term. zatw. wg harm.',
 'FUNC_AREA': 'Obszar funkcjonalny',
 'GAMNG': 'Ilość postulowana (GMEIN)',
 'GASMG': 'Łączna ilość braków (GMEIN)',
 'GETRI': 'Rzecz. termin zak.',
 'GEUZI': 'Rzeczywiste zakończ.',
 'GIAMG': 'Oczekiw. odchylenie (GMEIN)',
 'GLTPP': 'Termin zakończenia',
 'GLTPS': 'Zakończenie wg harm.',
 'GLTRI': 'Rzecz. termin zak.',
 'GLTRP': 'Baz.term.zak.',
 'GLTRS': 'Zakończenie wg harm.',
 'GLUZP': 'Bazowa godz. zakoń.',
 'GLUZS': 'Godz. zakoń. wg har.',
 'GMEIN': 'Jednostka miary (=GMEIN)',
 'GSBER': 'Dział gospodarczy',
 'GSBTR': 'Potwierdz. łączne',
 'GSTPP': 'Termin rozpocz.',
 'GSTPS': 'Rozpoczęcie wg harm.',
 'GSTRI': 'Rzecz. termin rozp.',
 'GSTRP': 'Baz. term. rozp.',
 'GSTRS': 'Rozpoczęcie wg harm.',
 'GSUZI': 'Rzecz.godz.rozp.',
 'GSUZP': 'Godzina rozpoczęcia',
 'GSUZS': 'Godz. rozp. wg harm.',
 'GWEMG': 'Ilość dostarczona (GMEIN)',
 'IASMG': 'Potwierdzone braki (GMEIN)',
 'ICON_MSGTY': 'Typ komunikatu',
 'ICON_ORDER_KIND': 'Ikona zlecenia',
 'IGMNG': 'Ilość potwierdzona (GMEIN)',
 'IMPMIN': 'Wpływ w minutach',
 'IVPRO': 'Profil inwestycyjny',
 'IZWEK': 'Powód inwestycji',
 'JV_JIBCL': 'Klasa JIB/JIBE',
 'JV_JIBSA': 'Podklasa A JIB/JIBE',
 'KALSM': 'Arkusz rozl. kosz.',
 'KALSN': 'Wybór kalendarza',
 'KAPVERSA': 'Wersja',
 'KDAUF_AUFK': 'Zlecenie klienta',
 'KDPOS_AUFK': 'Poz. w zlec. klienta',
 'KLVARI': 'War.kalk.kosztów rz.',
 'KLVARP': 'War.kalk.kosztów pl.',
 'KOKRS': 'Obszar rach. kosztów',
 'KOSTV': 'Odpowiedzialne MPK',
 'KSTAR': 'Rodzaj kosztów rozl.',
 'KSTEMPF': 'Zbieracz koszt.',
 'KTEXT': 'Krótki tekst',
 'KZAVC': 'Rodz. kontr. dostęp.',
 'KZERB': 'Agr. p. dane podst.',
 'LEAD_AUFNR': 'Zlecenie wiodące',
 'LGORT': 'Skład',
 'LOEKZ': 'Znacznik usuwania',
 'LTEXT': 'Opis istnieje',
 'MATNR': 'Numer materiału',
 'MATXT': 'Krótki tekst mater.',
 'MAUFNR': 'Zlecenie nadrzędne',
 'MDV01': 'Linia produkcyjna',
 'MDV02': 'ID planowania 2',
 'MILL_OC_ZUSKZ': 'Wskaźnik połączenia',
 'MILL_RATIO': 'Czynnik dostosowania dla reguły rozl.',
 'MIMEZ': 'Ocz.przyj.min./mak. (GMEIN)',
 'MSGTY': 'Typ komunikatu',
 'NOPCOST': 'Bez kosztów planow.',
 'OBJTYPE': 'Wskaźnik zmiany',
 'OTYPE': 'Typ obiektu-Joint Venture',
 'PAENR': 'Numer zmiany',
 'PDATV': 'Ważne od',
 'PERTR': 'Plan. data otwarcia',
 'PKOSA': 'Zbieracz kosztów pr.',
 'PLAUF': 'Data rozwinięcia',
 'PLGRP': 'Grupa planistów',
 'PLNAL': 'Licznik grupy',
 'PLNAW': 'Wykorz. marsz./planu',
 'PLNBEZ': 'Materiał',
 'PLNME': 'JM marszruty/planu (=PLNME)',
 'PLNNR': 'Grupa marszrut/plan.',
 'PLNTY': 'Typ marszruty/planu',
 'PLSVB': 'Wielkość partii do (PLNME)',
 'PLSVN': 'Wielkość partii od (PLNME)',
 'PLWRK': 'Zakład planowania',
 'PNETENDD': 'Zakończenie',
 'PNETENDT': 'Zakończenie',
 'PNETSTARTD': 'Rozpoczęcie',
 'PNETSTARTT': 'Rozpoczęcie',
 'POSNR_RMA': 'Pozycja (SD)',
 'POSNV_RMA': 'Pozycja (SD)',
 'PRCTR': 'Centrum zysku',
 'PROBCLASS': 'Maks. klasa problemu',
 'PROCNR': 'Numer procesu prod.',
 'PRODNET': 'Sieć zleceń',
 'PROJN': 'Element PSP',
 'PROTY': 'Typ procesu',
 'PROZENT': 'Procent (=PROZENT)',
 'PRUEFLOS': 'Partia kontrolna',
 'PSPEX': 'Identyfikacja',
 'RECID': 'Typ kosztów',
 'REDKZ': 'Wskaźnik redukcji',
 'REFNR': 'Zlecenie referenc.',
 'RETCODE': 'Wynik konroli dost.',
 'REVLV': 'Poziom zmian',
 'RMANR': 'Dokument SD',
 'RMNGA': 'Ilość poprawek (GMEIN)',
 'RSNUM': 'Rezerwacja',
 'RSORD': 'Zlecenie regeneracji',
 'RUECK': 'Potwierdzenie',
 'SAENR': 'Numer zmiany',
 'SAUFNR': 'Zlecenie seryjne',
 'SBMEH': 'Podst. jedn. miary (=SBMEH)',
 'SBMNG': 'Ilość podst. (SBMEH)',
 'SCOPE': 'Klasa obiektu',
 'SDATV': 'Ważne od',
 'SFCPF': 'Profil ster. prod.',
 'SICHZ': 'Poprod. rez. czasu',
 'SICHZ_TRM': 'Zapl. popr. zap. cz.',
 'SIZECL': 'Rząd wielkości',
 'SLSBS': 'Wielkość partii do (SBMEH)',
 'SLSVN': 'Wielkość partii od (SBMEH)',
 'SOBKZ': 'Zapas specjalny',
 'SOWRK': 'Zakład do lokaliz.',
 'SPLSTAT': 'Status podziału',
 'STATS': 'Schemat statusu',
 'STLAL': 'Alternatywa SpM',
 'STLAN': 'Wykorzystanie SpM',
 'STLBEZ': 'Materiał',
 'STLNR': 'Specyfikacja mater.',
 'STLST': 'Status SpM',
 'STLTY': 'Typ SpM',
 'STTXT': 'Status systemu',
 'ST_ARBID': 'ID obiektu',
 'TERHW': 'Wskazówka harmonogr.',
 'TERKZ': 'Rodz. harmonogramow.',
 'TRMDT': 'Harmonogram z',
 'UMWKZ': 'Inw. ochrony środow.',
 'UPDATE_CONTROL': 'Moment aktualiz. reklamacji',
 'UPDATE_NEEDED': 'Reklamacja nie jest spójna ze wsk. zlec.',
 'USER4': 'Koszty szacowane (WAERS)',
 'VERID': 'Wersja produkcji',
 'VFMNG': 'Ilość potwierdz. (GMEIN)',
 'VNAME': 'Joint venture',
 'VORGZ': 'PrzedprRezCzasu',
 'VORGZ_TRM': 'Zapl. zapas przedpr.',
 'VSNMR_V': 'Wersja',
 'WAERS': 'Waluta',
 'WERKS': 'Zakład',
 'YYVCMID': 'VCM Unikal. ID dla zlec. PP',
 'YYVCMPRCTR': 'Centrum zysku',
 'ZSCHL': 'Klucz narzutu',
 'ZZCHGPIC': 'Osoba odpowiedz.',
 'ZZDECDATE': 'Data odbioru',
 'ZZDECIDESC': 'Przyczyna odrzucenia',
 'ZZDECISION': 'Przyjęcie',
 'ZZDECPIC': 'Osoba odpowiedz.',
 'ZZMATNR': 'Materiał',
 'ZZREASON': 'Powód',
 'ZZREQUESTOR': 'Zlecający',
 'ZZREVLV': 'Poziom zmian',
 'ZZROMATNR': 'Materiał',
 'ZZSM_CARNR': 'Numer wagonu',
 'ZZSM_CARNR_CUST': 'Numer wagonu klienta',
 'ZZSM_SERNR': 'Nr rozwinięcia SpM',
 'ZZSM_TRAIN_NR': 'Numer wagonu',
 'ZZSM_UNDERFR_NR': 'Numer podwozia'}
