userColDict = {'AENNR': 'Numer zmiany',
 'ARBPL': 'St. rob.',
 'AUFNR': 'Nr zlec.',
 'BDMNG': 'Il.Zapotrz',
 'BDTER': 'Data zap.',
 'BERID': 'Obszar MRP',
 'BESKZ': 'Nabycie',
 'BOM_MATNR': 'Zespół',
 'DESCR': 'TekstOper',
 'DISPO': 'Kontr. MRP',
 'EKGRP': 'GrZaopatrz',
 'ENMNG': 'Il.pobrana',
 'ERR_MSG': 'Komunikat o błędzie',
 'FEVOR': 'PlanisProd',
 'KZKRI': 'K',
 'LABNR': 'Nr potw.',
 'LGORT': 'Skł.',
 'MAKTX': 'Oznacz.',
 'MANDT': 'Mnd',
 'MATNR': 'Komponent',
 'MEINS': 'JM',
 'MSTAE': 'SM',
 'PLNBEZ': 'Materiał',
 'POSNR': 'Poz.',
 'POTX1': 'Tekst poz.',
 'PRVBE': 'ObszZaopPr',
 'PSPEL': 'Elem. PSP',
 'RSART': 'TyR',
 'RSNUM': 'Rezerwacja',
 'RSPOS': 'Poz.',
 'SERNR': 'NrRozSpM',
 'SORTF': 'Łańc.sort.',
 'STATU': 'Status',
 'STTXT': 'Stat. sys.',
 'VMENG': 'Il. potw.',
 'VORNR': 'Operacja',
 'WERKS': 'Zakł',
 'XFEHL': 'Szacowane zlecenie zaległe',
 'XWAOK': 'Rch',
 'ZZCPF': 'Znacz.części głów.',
 'ZZCTC': 'Komentarz FP',
 'ZZDBU': 'JM',
 'ZZDOD': 'Data elementu odb.',
 'ZZDQY': 'Otwarta ilość w następnym elemencie odb.',
 'ZZPBF': 'Zaleg. zlec. pobr.',
 'ZZRBF': 'Rzecz. zaleg. zlec.',
 'ZZREN': 'Numer elementu odb.',
 'ZZRMC': 'Kontr. MRP',
 'ZZRTX': 'Powiązany/nast./ostatni rodz. elem. odb.',
 'ZZRTX1': 'Rodzaj zlecenia',
 'ZZSNO': 'Dostawca',
 'ZZSPN': 'Nazwa dostawcy'}
